coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5%
    patch:
      default:
        target: 70%

ignore:
  - "Nami/Views/**/*"  # SwiftUI views require UI tests
  - "NamiTests/**/*"   # Test files themselves

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
